image: node:22

stages:
  - test
  - secret-detection

unit-tests:
  stage: test
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  script:
    - npm ci
    - CI=true npm test
  only:
    - main
    - merge_requests

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'
