backend:
  name: github
  repo: username/repo-name # Nahraďte vaším uživatelským jménem a názvem repozitáře
  branch: main # Větev, kterou chcete spravovat
  base_url: https://your-github-pages-url.com # URL vašeho GitHub Pages webu
  auth_endpoint: api/auth # Endpoint pro OAuth

# Kde se budou ukládat média
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Definice kolekcí obsahu
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Datum publikace", name: "date", widget: "datetime" }
      - { label: "Popis", name: "description", widget: "text" }
      - { label: "Obsah", name: "body", widget: "markdown" }
